### ISSUE TITLE
提个小意见，如果能把注释保留就更好了

### ISSUE THREAD

**Issue by nxboo** [accforgit/TransVue2Ts#2]

**Comment by accforgit** [comment]
> _No description provided._

@nxboo  解析的时候专门过滤掉了注释，因为 babel 解析注释的时候，会把注释搞得乱七八糟，可能出现明明是上一行的注释，却给你换到下一行的情况，多行注释还可能只给你保留一半，错误的注释还不如没有，所以就过滤掉了，如果后续babel解决了这个问题，那么是可以加上的
