### ISSUE TITLE
请问一下有反向的库么？

### ISSUE THREAD

**Issue by Mister-Hope** [accforgit/TransVue2Ts#4]
请问有从ts到js的类似转换工具么？如果知道的话希望能回复一下，我找了一圈没有找到，如果没有就我只能自己写一个了。

需要的原因是要打包发布，使用ts编写的vue文件需要用户安装并配置好typescript比较麻烦，而且编译影响性能。

**Comment by accforgit** [comment]
没有反向的
比较好奇的是，为什么需要让用户安装和配置开发环境？你面向的用户是开发者吗？

**Comment by Mister-Hope** [comment]
> 没有反向的
> 比较好奇的是，为什么需要让用户安装和配置开发环境？你面向的用户是开发者吗？

emm，你可以看一下这个issue [建议去除用户端的 typescript 强依赖 #73](https://github.com/Mister-Hope/vuepress-theme-hope/issues/73)

**Comment by Mister-Hope** [comment]
你可以简单理解为我在开发一个组件库，我想使用ts开发，但是因为编译速度的问题我想交付js版的组件

**Comment by accforgit** [comment]
> 你可以简单理解为我在开发一个组件库，我想使用ts开发，但是因为编译速度的问题我想交付js版的组件

交付组件库的源码？

**Comment by Mister-Hope** [comment]
> > 你可以简单理解为我在开发一个组件库，我想使用ts开发，但是因为编译速度的问题我想交付js版的组件
> 
> 交付组件库的源码？

对的，vuepress基于webpack，用户使用我的组件库（主题）打包，ts速度会很慢。

说白了，我在做一个文档或者博客主题，vuepress是一个基于webpack的文档生成器，直接读取我的项目文件。

**Comment by accforgit** [comment]
> > > 你可以简单理解为我在开发一个组件库，我想使用ts开发，但是因为编译速度的问题我想交付js版的组件
> > 
> > 
> > 交付组件库的源码？
> 
> 对的，vuepress基于webpack，用户使用我的组件库（主题）打包，ts速度会很慢

了解了
