### ISSUE TITLE
可以将ts 再转回 js版本么？

### ISSUE THREAD

**Issue by zhongguagua** [accforgit/TransVue2Ts#9]

**Comment by accforgit** [comment]
理论上当然可以，但这个需求有点奇特，，，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "accforgit/TransVue2Ts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午3:20
收件人:&nbsp;"accforgit/TransVue2Ts"<TransVue2Ts@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[accforgit/TransVue2Ts] 可以将ts 再转回 js版本么？ (#9)
